version: "3"

tasks:
  setup:
    desc: Install all dependencies (Frontend & API)
    cmds:
      - npm install
      - cd api && npm install

  config:
    desc: Setup environment variables from templates
    cmds:
      - test -f .env || cp .env.example .env
      - test -f infra/terraform.tfvars || cp infra/terraform.tfvars.example infra/terraform.tfvars
      - echo "Configuration files created. Please edit .env and infra/terraform.tfvars with your actual data."
    status:
      - test -f .env
      - test -f infra/terraform.tfvars

  dev:
    desc: Run development server (Astro)
    cmds:
      - npm run dev

  build:
    desc: Build for production
    cmds:
      - npm run build

  infra:init:
    desc: Initialize Terraform
    dir: infra
    cmds:
      - terraform init

  infra:plan:
    desc: Show infrastructure changes
    dir: infra
    cmds:
      - terraform plan

  infra:apply:
    desc: Deploy infrastructure
    dir: infra
    cmds:
      - terraform apply -auto-approve

  container:build:
    desc: Build the site container image (Podman/Docker)
    cmds:
      - podman build -t helixcloud-web .

  container:run:
    desc: Run the site in a container
    cmds:
      - echo "Site will be available at http://localhost:8080"
      - podman run -d -p 8080:80 --name helixcloud-web helixcloud-web

  container:stop:
    desc: Stop and remove the site container
    cmds:
      - podman stop helixcloud-web && podman rm helixcloud-web

  clean:
    desc: Remove build artifacts and node_modules
    cmds:
      - rm -rf dist
      - rm -rf node_modules
      - rm -rf api/node_modules
